SELECT ENAME 
FROM emp 
INNER JOIN dept 
ON emp.DEPTNO = dept.DEPTNO 
WHERE dept.DNAME = "RESEARCH" 
AND HIREDATE IN (SELECT HIREDATE FROM emp, dept WHERE emp.DEPTNO = dept.DEPTNO AND DNAME = "SALES");