CREATE TABLE projet(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(5) NOT NULL);

/* CREATE TABLE projet(projetno INT NOT NULL PRIMARY KEY AUTO_INCREMENT, pname VARCHAR(5) NOT NULL, budget decimal(11,2)); */

/* ALTER TABLE projet AUTO-INCREMENT = 101; */

/* INSERT INTO projet VALUES (projetno, "ALPHA", 96000), (projetno, "BETA", 82000), (projetno, "GAMMA", 15000); */