DROP DATABASE if EXISTS db_ecf;

CREATE DATABASE db_ecf;

USE db_ecf;

CREATE TABLE realisations (
id_rea INT(10) UNSIGNED NOT NULL, 
titre_rea VARCHAR(255) NOT NULL, 
date_rea DATE NOT NULL, 
texte_rea TEXT NOT NULL 
) ENGINE=INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE images (
id_img INT(10) UNSIGNED NOT NULL, 
url_img VARCHAR(250) NOT NULL, 
nom_img VARCHAR(100), 
text_img VARCHAR(300) NOT NULL, 
ext_img VARCHAR(5) NOT NULL 
) ENGINE=INNODB DEFAULT CHARSET = UTF8;